#ifndef PINS_DEF
#define PINS_DEF
#define IR_SENSOR_PIN_PIN PIND
#define IR_SENSOR_PIN 13
#define IRMODE_LED_PIN 7
#define FEEDBACKPIN 15
#define CAMERA_CONTROL_PIN 6
#define MODE_BUTTON_PIN 8
#define ACTION_BUTTON_PIN 9
#define SOUND_SENSOR_PIN 10
#define MINUS_BUTTON_PIN 11
#define LASER_PIN 12
#define LASER_SENSOR_PIN A0
#endif
